databases:
  - name: franchise-db
    databaseName: franchise_db
    user: franchise_user
    plan: free

services:
  - type: web
    name: accenture-franchise-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: franchise-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: franchise-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: franchise-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: franchise-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: franchise-db
          property: password
      - key: SPRING_SQL_INIT_MODE
        value: always
